services:
  - type: web
    name: vandanam-school-portal
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: API_KEY
        sync: false